from .name_generator import NameGenerator

from .abbreviation_generator import AbbreviationGenerator
from .permute_generator import PermuteGenerator
from .prefix_generator import PrefixGenerator
from .suffix_generator import SuffixGenerator
from .wordnet_synonyms_generator import WordnetSynonymsGenerator
from .w2v_generator import W2VGenerator
from .categories_generator import CategoriesGenerator
from .random_generator import RandomGenerator
from .secondary_matcher import SecondaryMatcher
from .wikipedia2v_generator import Wikipedia2VGenerator
from .substringmatch_generator import SubstringMatchGenerator
